Develop
python52course/CatBotsApi pull request #2
Opened 2024-08-06 19:24 UTC by FuneralKitty

3 quest done
some changes in requirements

2024-08-06 19:31 UTC, kaziamov requested changes

2024-08-06 19:31 UTC, kaziamov commented on .idea/misc.xml
Файлы .idea/ должны быть в гитигноре

2024-08-06 19:31 UTC, kaziamov commented on Makefile
> +# .PHONY: app
Все что не используется и закоментировано не должно попадать в главную ветку. Либо создай новую ветку для этого, либо удали

2024-08-06 19:31 UTC, kaziamov commented on src/Third_quest.py
> +    return "Cats Service. Version 0.1", 200
Название сервиса лучше в переменную (можно даже в переменную окружения)

2024-08-06 19:31 UTC, kaziamov commented on src/First_quest.py
> +import psycopg2
Для этого модуля и других. Название должно отражать его функциональность, не причину почему он был создан

2024-08-06 19:31 UTC, kaziamov commented on src/First_quest.py
> +def first_quest():
То же самое касается касается названия переменных. То что это является номерами в задании не должно влиять на название частей приложения

2024-08-06 19:31 UTC, kaziamov commented on src/First_quest.py
> +                    INSERT INTO cat_colors_info (color, count)
Все запросы должны быть экранированы в целях безопасности

2024-08-06 19:31 UTC, kaziamov commented on src/First_quest.py
> +        print(f"Database error: {e}")
Вывод в консоль не должен использоваться, используй логгирование

2024-08-07 17:22 UTC, kaziamov requested changes

2024-08-07 17:22 UTC, kaziamov commented on .idea/misc.xml
этот файл тоже в игнор, можешь свю папку .idea поместить

2024-08-07 17:22 UTC, kaziamov commented on src/Third_quest.py
> +        conn = psycopg.connect(**DB_CONFIG)
запрос в базу лучше вынести из слоя роутинга

2024-08-07 17:22 UTC, kaziamov commented on src/config.py
> +    'dbname': 'wg_forge_db',
настройки базы нужно выносить в настройки окружения

2024-08-07 17:22 UTC, kaziamov commented on src/second_quest.py
> +        %s, %s, %s, %s, %s, %s
вот пример запроса с экранированием

2024-08-08 08:06 UTC, ApriCotBrain commented on src/Third_quest.py
> +    limit =  request.args.get("limit", default=10, type=int)
форматирование проверь пожалуйста, где-то двойные кавычки, где-то одинарные.

2024-08-08 08:06 UTC, ApriCotBrain commented on docker-compose.yml
> +  postgres_data:
Добавляй пустую строку в конец файла пожалуйста

2024-08-08 08:06 UTC, ApriCotBrain commented on src/First_quest.py
> +    first_quest()
Добавляй пустую строку в конец файла пожалуйста

2024-08-08 08:06 UTC, ApriCotBrain commented on src/Third_quest.py
> +                return jsonify({'error': 'No cats found'}), 404
возможно для кодов ответа в используемых инструментах есть переменные?

2024-08-08 08:06 UTC, ApriCotBrain commented on src/main.py
> +    second_quest()
пустая строка

2024-08-15 06:30 UTC, FuneralKitty commented on .gitignore
> +.idea/misc.xml
done

2024-08-15 06:35 UTC, FuneralKitty commented
done

2024-08-15 06:37 UTC, FuneralKitty commented
I think it`s done

2024-08-15 15:05 UTC, FuneralKitty commented on src/Third_quest.py
> +    return "Cats Service. Version 0.1", 200
done

2024-08-16 15:47 UTC, kaziamov requested changes

2024-08-16 15:47 UTC, kaziamov commented on src/data_fullfilling.py
> +        with psycopg.connect(**DB_CONFIG) as connection:
Заменить соединение на пул

2024-08-16 15:47 UTC, kaziamov commented on app.py
> +    db_request = f"""
Вынести логику из роутинга

2024-08-16 15:47 UTC, kaziamov commented on app.py
> +                {'name': cat[0], 'color': cat[1], 'tail_length': cat[2], 'whiskers_length': cat[3]}
Попробуй перевести на пайдантик модели (необязательно)

2024-08-16 15:47 UTC, kaziamov commented on app.py
> +    if 'name' not in data or not isinstance(data['name'], str):
Можно использовать модель

2024-08-16 15:47 UTC, kaziamov commented on app.py
> +def validate_attributes(data):
Добавить аннотацию типов

2024-08-16 15:47 UTC, kaziamov commented on src/config.py
> +    'host': 'postgres',
Нужно передавать извне

2024-08-16 15:47 UTC, kaziamov commented on src/config.py
> +    'port': '5432'
Нужно передавать извне

2024-08-16 15:47 UTC, kaziamov commented on src/data_fullfilling.py
> +                save_stats(
Попробуй запустить black или flake8

2024-08-17 07:36 UTC, FuneralKitty commented on app.py
> +    db_request = f"""
done

2024-08-17 09:13 UTC, kaziamov approved these changes

2024-08-17 09:13 UTC, kaziamov commented on app.py
> +pool = ConnectionPool(conninfo=f"dbname={DB_CONFIG['dbname']} user={DB_CONFIG['user']} password={DB_CONFIG['password']} host={DB_CONFIG['host']} port={DB_CONFIG['port']}")
Это лучше вынести в подходящий для этого модуль

2024-08-17 09:13 UTC, kaziamov commented on docker-compose.yml
> +    command: flask run --host=0.0.0.0 --port=8000
добавить --reload

2024-08-18 17:04 UTC, ApriCotBrain approved these changes
апрув, но в идеальной картине мира - хотелось бы  видеть пустые строки в конце файлов и корректный порядок импортов:-)

2024-08-19 09:07 UTC, FuneralKitty commented
Done

2024-08-20 15:17 UTC, RomanPecheritsa approved these changes

2024-08-20 15:18 UTC, merged

2024-08-20 15:18 UTC, hagp55 approved these changes

2024-08-20 15:18 UTC, hagp55 commented on Dockerfile
Правильнее будет сначала скопировать зависимости потом установить их, а потом еще раз добавить инструкцию add и скопировать основной код, так слои будут правильнее, и прийдется реже делать build, expose по моему можно убрать, он тут не особо нужен, compose откроет порты

2024-08-20 15:18 UTC, hagp55 commented on Makefile
Зачем docker-compose явно объявлен если используется стандартное имя файла, compose сам его подхватит

2024-08-20 15:18 UTC, hagp55 commented on app.py
> +from flask_limiter.util import get_remote_address
Порядок импортов сначала системные, потом сторонние библиотеки, потом импорты из локальных модулей, установи isort он тебе поможет

2024-08-20 15:18 UTC, hagp55 commented on app.py
> +def validate_attributes(data) -> tuple[Response, int] | None:
Добавить анатацию для параметра data

2024-08-20 15:18 UTC, hagp55 commented on docker-compose.yml
> +version: '3.3'
Версию уже необязательно указывать

2024-08-20 15:18 UTC, hagp55 commented on docker-compose.yml
> +      - ./postgres_data:/var/lib/postgresql
Посмотри как правильно указывать volume чтобы папка postgres_data внутри проекта не создавалась

2024-08-20 15:18 UTC, hagp55 commented on requirements.txt
Можно сделать отдельный requirements-dev чтобы там были дев зависимости

2024-08-20 15:18 UTC, hagp55 commented on src/data_fullfilling.py
> +valid_attributes: List[str] = ["name", "color", "tail_length", "whiskers_length"]
Константа в uppercase

2024-08-20 15:18 UTC, hagp55 commented on src/data_fullfilling.py
> +from config import DB_CONFIG
Сортировка импортов, в твоей версии python уже можно не импортировать базовые типы, и использовать dict вместо Dictionary

2024-08-20 15:18 UTC, hagp55 commented on src/data_fullfilling.py
> +    conninfo=f"dbname={DB_CONFIG['dbname']} user={DB_CONFIG['user']} password={DB_CONFIG['password']} host={DB_CONFIG['host']} port={DB_CONFIG['port']}"
Вместо вытаскивания значений из словаря, распакуй его **DB_CONFIG