Project works with docker
python52course/CatBotsApi pull request #4
Opened 2024-08-26 18:56 UTC by svereshagin

Project works with docker

2024-08-26 20:14 UTC, RomanPecheritsa approved these changes

2024-08-26 20:59 UTC, kaziamov requested changes

2024-08-26 20:59 UTC, kaziamov commented on .gitignore
> +.env/
Строчки дублируются

2024-08-26 20:59 UTC, kaziamov commented on requirements.txt
> +psycopg[binary]==3.2.1
Замени на psycopg2-binary. Удали из зависимостей pool

2024-08-26 20:59 UTC, kaziamov commented on src/config.py
> +    "host": 'postgres',
Порт и хост должны так же приходить из настроек окружения

2024-08-26 20:59 UTC, kaziamov commented on docker-compose.yml
>      image: postgres:latest
Фиксируй версию явно

2024-08-28 20:37 UTC, kaziamov approved these changes

2024-08-29 02:22 UTC, hagp55 approved these changes

2024-08-29 05:19 UTC, merged